package com.example.scyalladb.enums;


import com.example.scyalladb.enums.abstraction.ResponseCode;

public enum ApiResponseCode implements ResponseCode {

    SUCCESS(0,"SUCCESS"),
    ERROR(45,"ERROR"),
    INVALID_REQUEST(1,"INVALID_REQUEST"),
    INVALID_HASH_SID(2,"INVALID_HASH_SID"),
    INVALID_TOKEN(3, "INVALID_TOKEN"),
    TOKEN_EXPIRED(4, "TOKEN_EXPIRED"),
    OTHER(5, "OTHER"),
    SUBSCRIBER_NOT_FOUND(6, "SUBSCRIBER_NOT_FOUND"),
    SUBSCRIBER_STS_CANCELLED(7, "SUBSCRIBER_STS_CANCELLED"),
    PLATFORM_NOT_ALLOWED(8, "PLATFORM_NOT_ALLOWED"),
    UNKNOWN_PLATFORM(9, "UNKNOWN_PLATFORM"),
    LOGIN_REQUIRED(10, "LOGIN_REQUIRED"),
    SUBSCRIBER_STS_DEACTIVATE(11, "SUBSCRIBER_STS_DEACTIVATE"),
    UN_COMPATIBLE_VEDANTU_DIGITAL_VERSION(12,"UN_COMPATIBLE_VEDANTU_DIGITAL_VERSION"),
    ALREADY_EXISTS_3P_SUBSCRIPTION(13,"ALREADY_EXISTS_3P_SUBSCRIPTION"),
    PROMO_DISABLED(100,"PROMO_DISABLED"),
    UNKNOWN_PARTNER(14,"UNKNOWN_PARTNER"),
    UNKNOWN_REQUEST_FOR(15, "REQUEST_FOR_NOT_FOUND"),
    UNKNOWN_SUBSCRIBER_ID_FOR_PARTNER_ID(16, "PARTNER_ID_DOES_NOT_EXISTS_FOR_THIS_SUBSCRIBER_ID"),
    TOKEN_NOT_FOUND(17, "TOKEN_NOT_FOUND"),
    OFFER_ALREADY_AVAILED(24, "OFFER_ALREADY_AVAILED"),

    INVALID_SUBSCRIBER_ID(7007,"SUBSCRIBER_ID_INVALID."),
    INVALID_PACK_END_DATE(7004,"PACK_END_DATE_INVALID."),
    INVALID_PACK_FRIENDLY_NAME(7005,"PACK_FRIENDLY_NAME_INVALID."),
    INVALID_PACK_PRICE(7006,"PACK_PRICE_INVALID."),
    INVALID_SERVICE_TYPE(7008,"SERVICE_TYPE_IS_INVALID."),
    INVALID_ACTION_TYPE(7009,"ACTION_TYPE_IS_INVALID."),
    SUBSCRIBER_NOT_SUBSCRIBED_HUNGAMA_GAMES(20,"SUBSCRIBER_NOT_SUBSCRIBED_HUNGAMA_GAMES"),
    INVALID_CONTENT_TYPE(7010,"CONTENT_TYPE_IS_INVALID"),
    INVALID_MM_ID(7011,"MM_ID_IS_INVALID"),
    TABLE_NAME_NOT_FOUND(40,"BAD_REQUEST"),
    SUBSCRIBER_MISMATCH(21,"SUBSCRIBER_ID_MISMATCH"),
    INVALID_DATE_FORMAT(22,"INVALID_DATE_FORMAT"),
    SUBSCRIBER_NULL(23,"NULL_SUBSCRIBER_ID"),
    SUBSCRIBER_ID_NOT_NUMERIC(7012, "SUBSCRIBER_ID_NOT_NUMERIC"),
    CONTENT_ID_NOT_FOUND(7013, "CONTENT_ID_NOT_FOUND"),
    EPG_EVENT_TIME_OR_DATE(7014,"EPG_EVENT_TIME_OR_DATE"),
    RECHARGE_EVENT_STATUS(7015,"NOT_VALID_RECHARGE_EVENT_STATUS"),
    CHECKSUM_WRONG(7016, "CHECKSUM_WRONG"),
    REDIRECTION_FAILED(7017,"REDIRECTION_FAILED"),
    REDIRECTION_JOURNEY_TYPE_INVALID(7018,"REDIRECTION_JOURNEY_TYPE_INVALID"),
    PROCESSING_REQUEST_PLEASE_WAIT_FOR_SOME_TIME(7019,"PROCESSING_REQUEST_PLEASE_WAIT_FOR_SOME_TIME"),
    FETCH_IT_UPDATE_FAILED(7020,"FETCH_IT_UPDATE_FAILED");

    private int code;
    private String message;

    ApiResponseCode(int code, String message) {
        this.code = code;
        this.message = message;
    }

    @Override
    public int getCode() {
        return code;
    }

    @Override
    public String getMessage() {
        return message;
    }
}
